version: '3.8'
services:
  postgresqlDB:
    image: postgres
    restart: always
    container_name: stockDB
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    build: .
    image: stockbackend
    container_name: stockBACKEND
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgresqlDB
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresqlDB:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3001:3000"

networks:
  default:
      name: stock