global:
  scrape_interval:     15s # Default scrape interval

scrape_configs:
  - job_name: 'prometheus' # Job to scrape Prometheus metrics
    scrape_interval: 15s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus' # Job to scrape application metrics
    scrape_interval: 15s
    static_configs:
      - targets: ['stockBACKEND:8080']

  - job_name: 'spring-metrics'
    metrics_path: '/actuator/metrics' # Job to scrape custom metrics
    scrape_interval: 15s
    static_configs:
      - targets: ['stockBACKEND:8080']